DROP TABLE PICTURE;

CREATE TABLE  "PICTURE" 
   (	
   "NO" NUMBER, 
	"EMAIL" VARCHAR2(200), 
	"TITLE" VARCHAR2(200), 
	"IMAGE" VARCHAR2(200), 
	"CONTENT" VARCHAR2(2000), 
	"TIME" VARCHAR2(200), 
	"SEASON" VARCHAR2(200), 
	"WEATHER" VARCHAR2(200), 
	"LOCATION" VARCHAR2(400), 
	"REGDATE" DATE, 
	"LIKES" NUMBER, 
	 CONSTRAINT "PICTURE_PK" PRIMARY KEY ("NO") ENABLE, 
	 CONSTRAINT "PICTURE_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES  "MEMBER" ("EMAIL") ENABLE
   )