CREATE TABLE  "WEATHER" 
   (	"NO" NUMBER, 
	"X" NUMBER, 
	"Y" NUMBER, 
	"ADDRESS" VARCHAR2(400), 
	"CLIMATE" VARCHAR2(200), 
	"TEMP" VARCHAR2(200), 
	"TIME" VARCHAR2(100), 
	 CONSTRAINT "WEATHER_PK" PRIMARY KEY ("NO") ENABLE
   )
   
CREATE SEQUENCE   "WEATHER_NO_SEQ"  
MINVALUE 1 
MAXVALUE 99999999999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
NOORDER  
NOCYCLE
/