DROP TABLE WEATHER;

CREATE TABLE  "WEATHER" 
   (	
   "NO" NUMBER, 
   "EMAIL" VARCHAR2(200),
	"X" NUMBER, 
	"Y" NUMBER, 
	"ADDRESS" VARCHAR2(400), 
	"CLIMATE" VARCHAR2(200), 
	"TEMP" VARCHAR2(200), 
	"TIME" VARCHAR2(100), 
	 CONSTRAINT "WEATHER_PK" PRIMARY KEY ("NO") ENABLE,
	  CONSTRAINT "WEATHER_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES  "MEMBER" ("EMAIL") ENABLE
   );
   
CREATE SEQUENCE   "WEATHER_NO_SEQ"  
MINVALUE 1 
MAXVALUE 99999999999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
NOORDER  
NOCYCLE;


SELECT * FROM WEATHER;
DELETE FROM WEATHER;